const Laptop = [
    {   
        id : "1",
        name : "Hp 14s core i5 10th Gen 8gb/256gb ssd /windows 10",
        imgLink : "https://cdn.vox-cdn.com/thumbor/U9bVQsVE1qeyj04xJ-YAPuVheBw=/0x0:2040x1351/1200x800/filters:focal(857x513:1183x839)/cdn.vox-cdn.com/uploads/chorus_image/image/65169322/VLS_2759.0.jpg",
        DeletedPrice : "59900",
        price : "54000",
        Ratings : "5",
        redirect : "/laptop1",
        warrenty : "1 year",
        delivery : "50",
        battery_backup : "12 hrs",
        BatteryCell : "3 cell",
        model : "15s-GR0006AU",
        Series : "15s",
        color : "Jet Black",
        Ms_Office : "Yes",
        Processor : "AMD",
        Ram : "8 GB",
        SSD : "256 GB",
        HDD : "No",
        Os_Architecture : "64 bit",
        Mic : "yes",
        Rpm : "5400",
        ClockSpeed : "2.6 Ghz With turbo Boost Upto 3.5 Ghz",
        Screen_size : "39.4cm (15.6 Inch)",
        Screen_Resolution : "1366 X 768 pixel",
        WebCam : "Hp True Vision 720p HD webcam",
        FingerPrint : "No",
        Speaker : "Built-In Dual Speaker",
        Bluetooth : "V4.2",
        Weight : "1.76kg",
        DiskDrive : "NO",
        Warreny_Type : "Onsite",
        Not_Covered_Warrenty : "Physical damage",
        BackLight : "No",
        KeyFetures1 : "Stylish & Portable Thin Light Laptop",
        KeyFetures2 : "15.6 inch HD Led BackLit BrightView Micro-edge Display (220 nits Brightness,45% NTSC Color Gamut,101 PPI)",
        KeyFetures3 : "Light Laptop Without Optical Disk Drive",
        Manufacturer_origin : "China",
        Manufacturer_Details : "Tech Front (Chongqing) Computer Co. Ltd, No.18 , Zongboa Road , Shapingba Dist,Chongquing 401332,China",
        img1 : "",
        img2 : "",
        img3 : "",
        img4 : ""
    },

]

export default Laptop;